apiVersion: v2
name: microservice
description: A Helm chart for Kubernetes
type: application
version: 1.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresdb
    version: 1.0.0
    repository: https://baja-ks.github.io/Helm/stable
    condition: postgresdb.enabled
