apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name  }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.repo }}:{{ .Values.deployment.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: jwt-key
            - name: SEED_IF_EMPTY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: seed-empty
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-db-secret
                  key: db-user
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-db-secret 
                  key: db-password
            - name: DB_HOST 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-db-config
                  key: db-url
            - name: DB_DB 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-db-config
                  key: db-type
            - name: DB_PORT 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-db-config
                  key: db-port
            - name: DB_NAME 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-db-config 
                  key: db-name
            - name: SSL_MODE 
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-db-config 
                  key: db-ssl-mode
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{ end }}



